# Generated by Django 6.0.3 on 2026-06-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_form', '0005_experience_icon_name_herometric_icon_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g., Deloitte, Accenture', max_length=50)),
                ('platform_job_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('date_posted', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('platform_name', 'platform_job_id')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Match percentage from 0 to 100')),
                ('tags', models.JSONField(default=list, help_text='List of matching string tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_matches', to='jobby.job')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('portfolio', 'job')},
            },
        ),
    ]
