# Generated by Codex on 2026-07-01

from django.db import migrations, models


def copy_match_tags_to_jobs(apps, schema_editor):
    Job = apps.get_model("jobby", "Job")
    PortfolioJobMatch = apps.get_model("jobby", "PortfolioJobMatch")

    best_tags_by_job_id = {}
    matches = PortfolioJobMatch.objects.exclude(tags=[]).values("job_id", "tags")
    for match in matches:
        tags = match.get("tags") or []
        if not isinstance(tags, list) or not tags:
            continue

        current = best_tags_by_job_id.get(match["job_id"], [])
        if len(tags) > len(current):
            best_tags_by_job_id[match["job_id"]] = tags

    for job_id, tags in best_tags_by_job_id.items():
        Job.objects.filter(pk=job_id).filter(tags=[]).update(tags=tags)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("jobby", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ai_metadata",
            field=models.JSONField(blank=True, default=dict, help_text="Stable AI-generated job metadata"),
        ),
        migrations.AddField(
            model_name="job",
            name="ai_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.JSONField(default=list, help_text="Stable AI-generated job tags"),
        ),
        migrations.RunPython(copy_match_tags_to_jobs, noop_reverse),
        migrations.RemoveField(
            model_name="portfoliojobmatch",
            name="tags",
        ),
    ]
