# Generated by Django 6.0.3 on 2026-04-05 15:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import portfolio_form.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Primary identifier for login and OTP.', max_length=254, unique=True)),
                ('tier', models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], default=0)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('theme_mode', models.IntegerField(choices=[(0, 'Ocean'), (1, 'Forest'), (2, 'Desert'), (3, 'Space'), (4, 'Sunset')], default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email via OTP.')),
                ('enable_share_token', models.BooleanField(default=False, help_text='Toggle to make the portfolio publicly accessible.')),
                ('share_token', models.CharField(default=portfolio_form.models.generate_share_token, editable=False, help_text='The unique slug used in the public portfolio URL.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tier', models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], default=0)),
                ('name', models.CharField(default='Soham Dutta', max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('hero_eyebrow', models.CharField(max_length=100)),
                ('hero_title', models.TextField()),
                ('hero_description', models.TextField()),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('NAV', 'Navigation'), ('FOOTER', 'Footer'), ('CONTACT', 'Contact Method'), ('STATUS', 'Status Pill')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('href', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('icon_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('details', models.TextField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('related_components', models.JSONField(default=list)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('for_work', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('display_index', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['display_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('eyebrow', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stat', models.CharField(max_length=100)),
                ('stack', models.JSONField(default=list)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('icon_name', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('relation', models.CharField(max_length=100)),
                ('preview', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'verbose_name_plural': 'Showcase Categories',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='portfolio_form.portfoliosettings')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='portfoliosettings',
            constraint=models.UniqueConstraint(fields=('owner', 'order_index'), name='unique_portfolio_settings_per_owner_index'),
        ),
        migrations.AddConstraint(
            model_name='contactformsubmission',
            constraint=models.UniqueConstraint(fields=('owner', 'display_index'), name='unique_submission_index_per_owner'),
        ),
    ]
