# Generated by Django 6.0.3 on 2026-04-08 21:33

import portfolio_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='hero_actions',
            field=models.JSONField(default=portfolio_form.models.default_hero_actions),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='hero_badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='hero_focus',
            field=models.JSONField(default=portfolio_form.models.default_hero_focus),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='hero_highlights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='page_copy',
            field=models.JSONField(default=portfolio_form.models.default_page_copy),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='section_copy',
            field=models.JSONField(default=portfolio_form.models.default_section_copy),
        ),
    ]
