# Generated by Django 6.0.3 on 2026-05-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0002_portfoliosettings_hero_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Text to display on the action button', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='href',
            field=models.CharField(blank=True, help_text='Target URL or anchor link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name string', max_length=50, null=True),
        ),
    ]
