# Generated by Django 6.0.3 on 2026-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0003_project_cta_label_project_href_project_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
