# Generated by Django 6.0.3 on 2026-05-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0004_portfoliosettings_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herometric',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillgroup',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='featuredmodule',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='about_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='about_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='hero_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='hero_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showcasecategory',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
    ]
