# Generated by Django 6.0.3 on 2026-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0004_user_dashboard_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0),
        ),
    ]
