# Generated by Django 6.0.3 on 2026-07-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0005_experience_icon_name_herometric_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_analysis_limit',
            field=models.PositiveIntegerField(default=2, help_text='The maximum number of job analyses a user can perform.'),
        ),
    ]
