# Generated by Django 6.0.3 on 2026-04-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0006_experience_featuredmodule_herometric_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='share_token',
        ),
        migrations.AddField(
            model_name='user',
            name='enable_share_token',
            field=models.BooleanField(default=False),
        ),
    ]
