# Generated by Django 6.0.3 on 2026-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0009_alter_portfoliosettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], default=0),
        ),
    ]
