# Generated by Django 6.0.3 on 2026-04-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0010_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
