# Generated by Django 6.0.3 on 2026-04-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0011_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
