# Generated by Django 6.0.3 on 2026-04-04 12:32

import portfolio_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='showcasecategory',
            name='icon_name',
            field=models.CharField(help_text='Lucide icon name', max_length=50),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Primary identifier for login and OTP.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='enable_share_token',
            field=models.BooleanField(default=False, help_text='Toggle to make the portfolio publicly accessible.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email via OTP.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='share_token',
            field=models.CharField(default=portfolio_form.models.generate_share_token, editable=False, help_text='The unique slug used in the public portfolio URL.', max_length=64, unique=True),
        ),
    ]
