# Generated by Django 6.0.3 on 2026-04-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_form', '0013_alter_link_options_user_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.IntegerField(choices=[(0, 'Ocean'), (1, 'Forest'), (2, 'Desert'), (3, 'Space'), (4, 'Sunset')], default=0),
        ),
    ]
